### ISSUE TITLE
java.lang.NullPointerException    at fi.helsinki.cs.tmc.model.ProjectMediator.tryGetExerciseForProject(ProjectMediator.java:126)

### ISSUE THREAD

**Issue by markiewb** [testmycode/tmc-netbeans#130]
```
java.lang.NullPointerException
   at fi.helsinki.cs.tmc.model.ProjectMediator.tryGetExerciseForProject(ProjectMediator.java:126)
   at fi.helsinki.cs.tmc.spyware.eventsources.WindowStatechangesEventSource.getExercise(WindowStatechangesEventSource.java:153)
   at fi.helsinki.cs.tmc.spyware.eventsources.WindowStatechangesEventSource.propertyChange(WindowStatechangesEventSource.java:65)
   at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
   at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
   at org.netbeans.api.editor.EditorRegistry.fireEvents(EditorRegistry.java:544)
```
https://netbeans.org/bugzilla/show_bug.cgi?id=256917

**Comment by jamox** [comment]
Thanks for bringing this to our attention, I'll fix that shortly.

**Comment by markiewb** [comment]
You are welcome! You can also search the bugtracker for more reported issues.

**Comment by markiewb** [comment]
or even the exceptions reporter: http://statistics.netbeans.org/exceptions/
